version: "3"

services:
  app:
    build:
      context: app
    ports:
      - "5000"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "81:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf

# web service: This is where your Flask application runs. It's built from the Dockerfile defined in the same directory.
# nginx service: This uses the official NGINX image and mounts the nginx.conf file into the container, allowing NGINX to read the configuration.
# Port Mapping: Port 80 on the host is mapped to port 80 in the NGINX container, making the application accessible via HTTP.
# extension to docker, to allow u run multiple services on asingle app 