version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5001:5000"

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf